name: CI shop server

on: push

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
